foreground         #cfc8c5
background         #0c0c0c
background_opacity 1.0
cursor             #cfc8c5

active_tab_foreground     #0c0c0c
active_tab_background     #cfc8c5
inactive_tab_foreground   #cfc8c5
inactive_tab_background   #0c0c0c

active_border_color   #cfc8c5
inactive_border_color #0c0c0c
bell_border_color     #564A38

color0       #0c0c0c
color8       #908c89
color1       #564A38
color9       #564A38
color2       #635F5B
color10      #635F5B
color3       #8E2626
color11      #8E2626
color4       #AB3132
color12      #AB3132
color5       #AF5F53
color13      #AF5F53
color6       #B79D69
color14      #B79D69
color7       #cfc8c5
color15      #cfc8c5
