general {
    lock_cmd = ""
}

listener {
    timeout    = 300                # 5 minutes
    on-timeout = ~/.config/hypr/hyprlock/hyprlock.sh
    on-resume  = ""                       # no action needed when you return
}

listener { # complete black display
    timeout = 180 # 4mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
