-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("linear",           { type = "bezier", points = { {0,    0},   {1,    1}   } })
hl.curve("overshot",         { type = "bezier", points = { {0.01, 0.9}, {0.5,  1.1} } })
hl.curve("overshot-slow",    { type = "bezier", points = { {0.01, 0.7}, {0.01, 0.5} } })
hl.curve("emphasizedDecel",  { type = "bezier", points = { {0.05, 0.7}, {0.1,  1}   } })
hl.curve("easeOutCubic",     { type = "bezier", points = { {0.33, 1},   {0.68, 1}   } })

hl.animation({ leaf = "windows",          enabled = true, speed = 3,   bezier = "overshot",        style = "slide" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 2,   bezier = "emphasizedDecel", style = "slide" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 8,   bezier = "easeOutCubic",    style = "popin 40%" })
hl.animation({ leaf = "border",           enabled = true, speed = 10,  bezier = "default" })
hl.animation({ leaf = "fade",             enabled = true, speed = 0.1, bezier = "default" })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 8,   bezier = "default" })
hl.animation({ leaf = "fadeLayersIn",     enabled = true, speed = 2,   bezier = "overshot" })
hl.animation({ leaf = "fadeLayersOut",    enabled = true, speed = 0.5, bezier = "overshot" })
hl.animation({ leaf = "layers",           enabled = true, speed = 1.5, bezier = "overshot",        style = "slide" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 1,   bezier = "overshot",        style = "slide top" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 1,   bezier = "default" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 2,   bezier = "overshot",        style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3,   bezier = "overshot",        style = "slidefadevert" })