# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = hyprctl setcursor Bibata-Modern-Ice 24 # cursor
exec-once = swaync & qs & swww-daemon
exec-once = cliphist wipe # reset cliphist for security
exec-once = wl-paste --watch cliphist store
exec-once = ~/.config/hypr/wallpapers/reload_wallpaper.sh
exec-once = ~/.config/hypr/hyprlock/hyprlock.sh
exec-once = docker ps # load docker containers.
exec-once = hypridle
exec-once = flameshot
# ensure plugins (and their dispatchers) are loaded before binds
exec-once = hyprpm reload -n