####################
### Window rules ###
####################
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/

### Important Fixes ###

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

### Apps ###

# stay focused app menu
windowrulev2 = stayfocused, class:(rofi|wofi|Vncviewer)
windowrulev2 = center, class:(Vncviewer)


# flameshot multi-display fix
windowrulev2 = move 0 0,class:(flameshot),title:(flameshot)
windowrulev2 = pin,class:(flameshot),title:(flameshot)
windowrulev2 = fullscreenstate,class:(flameshot),title:(flameshot)
windowrulev2 = float,class:(flameshot),title:(flameshot)

# pavucontrol - audio
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = center, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 1200 700, class:^(org.pulseaudio.pavucontrol)$
# blueman manager
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = center, class:^(blueman-manager)$
windowrulev2 = size 800 500, class:^(blueman-manager)$
# IW GTK 
windowrulev2 = float, class:^(org.twosheds.iwgtk)$
windowrulev2 = center, class:^(org.twosheds.iwgtk)$
windowrulev2 = size 1200 700, class:^(org.twosheds.iwgtk)$

### Custom rules ###

# custom hover class rules
windowrulev2 = float, class:custom_hover
windowrulev2 = center, class:custom_hover
windowrulev2 = size 1200 650, class:custom_hover
windowrulev2 = animation slide bottom, class:custom_hover
windowrulev2 = rounding 10, class:custom_hover

#################
### Workspace ###
#################
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# custom Workspace / default, Laptop
workspace = name:default, monitor:eDP-1, defaultName:default, persistent:true
workspace = special:exposed,gapsout:60,gapsin:30,bordersize:5,border:true,shadow:false
workspace = name:default, monitor:eDP-1


###################
### Layer rules ###
###################
# Window/layer rules: https://wiki.hypr.land/Configuring/Window-Rules/#layer-rules

layerrule = blur on, match:class quickshell
layerrule = ignore_alpha 0.5, match:class quickshell

layerrule = blur on, match:class waybar
layerrule = ignore_alpha 0.5, match:class waybar

layerrule = blur on, match:class wofi
layerrule = ignore_alpha 0.5, match:class wofi

layerrule = blur on, match:class swaync-control-center
layerrule = blur on, match:class swaync-notification-window
layerrule = ignore_alpha 0.5, match:class swaync-control-center
layerrule = ignore_alpha 0.5, match:class swaync-notification-window

layerrule = no_anim on, match:class logout_dialog