####################
### Window rules ###
####################
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/

### Important Fixes ###
# Ignore maximize requests
windowrule = match:class .*, suppress_event maximize

# Fix dragging issues (no_focus needs 'on' or '1')
windowrule = match:class ^$ match:title ^$ match:xwayland 1 match:floating 1, no_focus on

### Apps ###

# stay focused app menu
windowrule = match:class (rofi|wofi|Vncviewer), stay_focused on
windowrule = match:class (Vncviewer), center on

# flameshot multi-display fix
windowrule {
    name = flameshot-multi-display-fix
    match:class = flameshot

    animation = fade
    rounding = 0
    border_size = 0
    fullscreen_state = 0 0
    float = on
    pin = on
    monitor = DP-1
    move = 0 0
    size = (monitor_w*2) (monitor_h)
}
# pavucontrol - audio
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, center on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size 1200 700

# blueman manager
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, center on
windowrule = match:class ^(blueman-manager)$, size 800 500

# Calculator
windowrule = match:class ^(org.gnome.Calculator)$, float on
windowrule = match:class ^(org.gnome.Calculator)$, center on
windowrule = match:class ^(org.gnome.Calculator)$, size 385 616

# IW GTK 
windowrule = match:class ^(org.twosheds.iwgtk)$, float on
windowrule = match:class ^(org.twosheds.iwgtk)$, center on
windowrule = match:class ^(org.twosheds.iwgtk)$, size 1200 700

# xdg-desktop-portal-gtk
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, center on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, size 1200 700
windowrule = match:class ^(xdg-desktop-portal-gtk)$, animation slide bottom

### Custom rules ###
windowrule = match:class custom_hover, float on
windowrule = match:class custom_hover, center on
windowrule = match:class custom_hover, size 1200 650
windowrule = match:class custom_hover, animation slide bottom
windowrule = match:class custom_hover, rounding 10

#################
### Workspace ###
#################
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# custom Workspace / default, Laptop
workspace = name:default, monitor:eDP-1, defaultName:default, persistent:true
workspace = special:exposed,gapsout:60,gapsin:30,bordersize:5,border:true,shadow:false
workspace = name:default, monitor:eDP-1

workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true

###################
### Layer rules ###
###################
# Window/layer rules: https://wiki.hypr.land/Configuring/Window-Rules/#layer-rules

layerrule = blur on, match:class quickshell
layerrule = ignore_alpha 0.5, match:class quickshell

layerrule = blur on, match:class waybar
layerrule = ignore_alpha 0.5, match:class waybar

layerrule = blur on, match:class wofi
layerrule = ignore_alpha 0.5, match:class wofi

layerrule = blur on, match:class swaync-control-center
layerrule = blur on, match:class swaync-notification-window
layerrule = ignore_alpha 0.5, match:class swaync-control-center
layerrule = ignore_alpha 0.5, match:class swaync-notification-window

layerrule = no_anim on, match:class logout_dialog
