############
### Exec ###
############

# GUI APPS
# exec-once = codium & obsidian & steam & vesktop & thunderbird & zen-browser

####################
### Window rules ###
####################

## workspace rules
# windowrulev2 = workspace 1, class:^(zen)$
# windowrulev2 = workspace 2, class:^(RemoteDesktopManager)$
# windowrulev2 = workspace 3, class:^(teams-for-linux|KeePassXC|obsidian|VSCodium)$
# windowrulev2 = workspace 9, class:^(xfreerdp)$

###############################
### Monitor/Workspace setup ###
###############################

# workspaces
# workspace = 1, monitor:desc:AOC Q27P2W ASEQ59A000131
# workspace = 2, monitor:desc:AOC Q27P2W ASEQ59A000131
# workspace = 3, monitor:desc:AOC Q27P2W ASEQ59A000131
# workspace = 4, monitor:desc:AOC Q27P2W ASEQ59A000131
# workspace = 5, monitor:desc:AOC Q27P2W ASEQ59A000131
# workspace = 6, monitor:desc:AOC Q27P2W ASEQ59A000131
# workspace = 7, monitor:desc:AOC Q27P2W ASEQ59A000131
# workspace = 8, monitor:desc:AOC Q27P2W ASEQ59A000698
# workspace = 9, monitor:desc:AOC Q27P2W ASEQ59A000698
# workspace = 0, monitor:desc:AOC Q27P2W ASEQ59A000698
